openapi: "3.0.1"
info:
  version: "1.0.0"
  title: "Ejemplo API"

paths:
  /clientes:
    get:
      summary: "Obtener todos los clientes"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Cliente"
    post:
      summary: "Crear un nuevo cliente"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cliente"
      responses:
        "201":
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cliente"
  /clientes/{id}:
    get:
      summary: Obtener un cliente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID del cliente a obtener
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Cliente encontrado
        "404":
          description: Cliente no encontrado
  /clientes/editar/{id}:
    put:
      summary: Actualizar un cliente existente
      parameters:
        - name: id
          in: path
          required: true
          description: ID del cliente a actualizar
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cliente"
      responses:
        "200":
          description: Cliente actualizado exitosamente
        "404":
          description: Cliente no encontrado
        "400":
          description: Solicitud inválida
  /clientes/eliminar/{id}:
    delete:
      summary: Eliminar un cliente existente
      parameters:
        - name: id
          in: path
          required: true
          description: ID del cliente a eliminar
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Cliente eliminado exitosamente
        "404":
          description: Cliente no encontrado
#---------------------------------------------
#Se declaran los Modelos/Schemas del servicio
#---------------------------------------------
components:
  schemas:
    ClienteBaseType:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        numeroCliente:
          type: "integer"
        tipoPersona:
          type: "string"
        tipoDocumento:
          type: "string"
        numeroDocumento:
          type: "integer"
        fechaExpedicionDocumento:
          type: "string"
          format: "date"
        primerNombre:
          type: "string"
        numeroCelular:
          type: "integer"
        segundoNombre:
          type: "string"
        primerApellido:
          type: "string"
        segundoApellido:
          type: "string"
        correoElectronico:
          type: "string"
